name: Auto Merge Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge pull request
        run: |
          git config --global user.email "vaishak101@gmail.com"
          git config --global user.name "Vaishak Nair"

          if [[ "origin/${{ github.event.pull_request.head.ref }}" == "origin/feature"* || "origin/${{ github.event.pull_request.head.ref }}" == "origin/bugs"* ]]; then
            git fetch origin
            git checkout dev
            git merge --no-ff "origin/${{ github.event.pull_request.head.ref }}" -m "Auto merge pull request #${{ github.event.pull_request.number }}"
            git push origin dev
          fi
